name: Backend API
on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Form data JSON'
        required: true
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up SQLite
        uses: actions/setup-sqlite@v1
        with:
          sqlite-version: 3.47.2
          sqlite-year: 2024
      - name: Process Payload
        run: |
          sqlite3 data.db "INSERT INTO messages (name, message) VALUES ('${{ github.event.inputs.payload.name }}', '${{ github.event.inputs.payload.message }}')"
      - name: Commit Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data.db
          git commit -m "Update database with new entry"
          git push
