# .github/workflows/backend.yml

name: Update Guestbook Database Backend API

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the guest"
        required: true
        type: string
      message:
        description: "Guest message"
        required: true
        type: string

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install sqlite3 CLI
      run: sudo apt-get update && sudo apt-get install -y sqlite3

    - name: Insert guestbook entry
      run: |
        echo "Inserting into database..."
        sqlite3 data.db "CREATE TABLE IF NOT EXISTS guestbook (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"
        sqlite3 data.db "INSERT INTO guestbook (name, message) VALUES ('$NAME', '$MESSAGE');"
      env:
        NAME: ${{ inputs.name }}
        MESSAGE: ${{ inputs.message }}

    - name: Commit and push database
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data.db
        git commit -m "Update guestbook: add message from $NAME"
        git push
      env:
        NAME: ${{ inputs.name }}

